/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as BuildsRouteImport } from './routes/builds'
import { Route as CacheRouteImport } from './routes/cache'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ArtifactsIndexRouteImport } from './routes/artifacts.index'
import { Route as ArtifactsComponentIdRouteImport } from './routes/artifacts.$componentId'
import { Route as ArtifactsSettingsRouteImport } from './routes/artifacts.settings'
import { Route as BuildsIndexRouteImport } from './routes/builds.index'
import { Route as BuildsJobIdRouteImport } from './routes/builds.$jobId'
import { Route as InviteInvitationIdRouteImport } from './routes/invite.$invitationId'
import { Route as PipelinesPipelineIdRouteImport } from './routes/pipelines.$pipelineId'
import { Route as ProjectsProjectNameRouteImport } from './routes/projects.$projectName'
import { Route as ReleasesIndexRouteImport } from './routes/releases.index'
import { Route as ReleasesReleaseNameRouteImport } from './routes/releases.$releaseName'
import { Route as ReleasesArtifactsRouteImport } from './routes/releases.artifacts'
import { Route as ReleasesCalendarRouteImport } from './routes/releases.calendar'
import { Route as SecretsIndexRouteImport } from './routes/secrets.index'
import { Route as SecretsSecretIdRouteImport } from './routes/secrets.$secretId'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsOrganizationRouteImport } from './routes/settings.organization'
import { Route as WorkersBuildsRouteImport } from './routes/workers.builds'
import { Route as WorkersDeploymentsRouteImport } from './routes/workers.deployments'
import { Route as WorkersOverviewRouteImport } from './routes/workers.overview'
import { Route as WorkersPersistentvolumeclaimsRouteImport } from './routes/workers.persistentvolumeclaims'
import { Route as WorkersPodsRouteImport } from './routes/workers.pods'
import { Route as WorkersProjectsRouteImport } from './routes/workers.projects'
import { Route as WorkersRoutesRouteImport } from './routes/workers.routes'
import { Route as WorkersServicesRouteImport } from './routes/workers.services'
import { Route as ApiSessionSplatRouteImport } from './routes/api/session/$'
import { Route as BuildsJobIdIndexRouteImport } from './routes/builds.$jobId.index'
import { Route as ProjectsProjectNameIndexRouteImport } from './routes/projects.$projectName.index'
import { Route as ProjectsProjectNameBranchesRouteImport } from './routes/projects.$projectName.branches'
import { Route as ProjectsProjectNameTagsRouteImport } from './routes/projects.$projectName.tags'
import { Route as WorkersBuildsIndexRouteImport } from './routes/workers.builds.index'
import { Route as WorkersBuildsBuildNameRouteImport } from './routes/workers.builds.$buildName'
import { Route as WorkersDeploymentsIndexRouteImport } from './routes/workers.deployments.index'
import { Route as WorkersDeploymentsDeploymentNameRouteImport } from './routes/workers.deployments.$deploymentName'
import { Route as WorkersPersistentvolumeclaimsIndexRouteImport } from './routes/workers.persistentvolumeclaims.index'
import { Route as WorkersPersistentvolumeclaimsClaimNameRouteImport } from './routes/workers.persistentvolumeclaims.$claimName'
import { Route as WorkersPodsIndexRouteImport } from './routes/workers.pods.index'
import { Route as WorkersPodsPodNameRouteImport } from './routes/workers.pods.$podName'
import { Route as WorkersProjectsIndexRouteImport } from './routes/workers.projects.index'
import { Route as WorkersProjectsProjectNameRouteImport } from './routes/workers.projects.$projectName'
import { Route as WorkersRoutesIndexRouteImport } from './routes/workers.routes.index'
import { Route as WorkersRoutesRouteNameRouteImport } from './routes/workers.routes.$routeName'
import { Route as WorkersServicesIndexRouteImport } from './routes/workers.services.index'
import { Route as WorkersServicesServiceNameRouteImport } from './routes/workers.services.$serviceName'
import { Route as BuildsJobIdBuildsBuildIdRouteImport } from './routes/builds.$jobId.builds.$buildId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsRoute = BuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const CacheRoute = CacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsIndexRoute = ArtifactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtifactsRoute,
} as any)
const ArtifactsComponentIdRoute = ArtifactsComponentIdRouteImport.update({
  id: '/$componentId',
  path: '/$componentId',
  getParentRoute: () => ArtifactsRoute,
} as any)
const ArtifactsSettingsRoute = ArtifactsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ArtifactsRoute,
} as any)
const BuildsIndexRoute = BuildsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuildsRoute,
} as any)
const BuildsJobIdRoute = BuildsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => BuildsRoute,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesPipelineIdRoute = PipelinesPipelineIdRouteImport.update({
  id: '/$pipelineId',
  path: '/$pipelineId',
  getParentRoute: () => PipelinesRoute,
} as any)
const ProjectsProjectNameRoute = ProjectsProjectNameRouteImport.update({
  id: '/$projectName',
  path: '/$projectName',
  getParentRoute: () => ProjectsRoute,
} as any)
const ReleasesIndexRoute = ReleasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReleasesRoute,
} as any)
const ReleasesReleaseNameRoute = ReleasesReleaseNameRouteImport.update({
  id: '/$releaseName',
  path: '/$releaseName',
  getParentRoute: () => ReleasesRoute,
} as any)
const ReleasesArtifactsRoute = ReleasesArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => ReleasesRoute,
} as any)
const ReleasesCalendarRoute = ReleasesCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ReleasesRoute,
} as any)
const SecretsIndexRoute = SecretsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecretsRoute,
} as any)
const SecretsSecretIdRoute = SecretsSecretIdRouteImport.update({
  id: '/$secretId',
  path: '/$secretId',
  getParentRoute: () => SecretsRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOrganizationRoute = SettingsOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => SettingsRoute,
} as any)
const WorkersBuildsRoute = WorkersBuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => WorkersRoute,
} as any)
const WorkersDeploymentsRoute = WorkersDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => WorkersRoute,
} as any)
const WorkersOverviewRoute = WorkersOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => WorkersRoute,
} as any)
const WorkersPersistentvolumeclaimsRoute =
  WorkersPersistentvolumeclaimsRouteImport.update({
    id: '/persistentvolumeclaims',
    path: '/persistentvolumeclaims',
    getParentRoute: () => WorkersRoute,
  } as any)
const WorkersPodsRoute = WorkersPodsRouteImport.update({
  id: '/pods',
  path: '/pods',
  getParentRoute: () => WorkersRoute,
} as any)
const WorkersProjectsRoute = WorkersProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => WorkersRoute,
} as any)
const WorkersRoutesRoute = WorkersRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => WorkersRoute,
} as any)
const WorkersServicesRoute = WorkersServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => WorkersRoute,
} as any)
const ApiSessionSplatRoute = ApiSessionSplatRouteImport.update({
  id: '/api/session/$',
  path: '/api/session/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsJobIdIndexRoute = BuildsJobIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuildsJobIdRoute,
} as any)
const ProjectsProjectNameIndexRoute =
  ProjectsProjectNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectNameRoute,
  } as any)
const ProjectsProjectNameBranchesRoute =
  ProjectsProjectNameBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => ProjectsProjectNameRoute,
  } as any)
const ProjectsProjectNameTagsRoute = ProjectsProjectNameTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => ProjectsProjectNameRoute,
} as any)
const WorkersBuildsIndexRoute = WorkersBuildsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkersBuildsRoute,
} as any)
const WorkersBuildsBuildNameRoute = WorkersBuildsBuildNameRouteImport.update({
  id: '/$buildName',
  path: '/$buildName',
  getParentRoute: () => WorkersBuildsRoute,
} as any)
const WorkersDeploymentsIndexRoute = WorkersDeploymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkersDeploymentsRoute,
} as any)
const WorkersDeploymentsDeploymentNameRoute =
  WorkersDeploymentsDeploymentNameRouteImport.update({
    id: '/$deploymentName',
    path: '/$deploymentName',
    getParentRoute: () => WorkersDeploymentsRoute,
  } as any)
const WorkersPersistentvolumeclaimsIndexRoute =
  WorkersPersistentvolumeclaimsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkersPersistentvolumeclaimsRoute,
  } as any)
const WorkersPersistentvolumeclaimsClaimNameRoute =
  WorkersPersistentvolumeclaimsClaimNameRouteImport.update({
    id: '/$claimName',
    path: '/$claimName',
    getParentRoute: () => WorkersPersistentvolumeclaimsRoute,
  } as any)
const WorkersPodsIndexRoute = WorkersPodsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkersPodsRoute,
} as any)
const WorkersPodsPodNameRoute = WorkersPodsPodNameRouteImport.update({
  id: '/$podName',
  path: '/$podName',
  getParentRoute: () => WorkersPodsRoute,
} as any)
const WorkersProjectsIndexRoute = WorkersProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkersProjectsRoute,
} as any)
const WorkersProjectsProjectNameRoute =
  WorkersProjectsProjectNameRouteImport.update({
    id: '/$projectName',
    path: '/$projectName',
    getParentRoute: () => WorkersProjectsRoute,
  } as any)
const WorkersRoutesIndexRoute = WorkersRoutesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkersRoutesRoute,
} as any)
const WorkersRoutesRouteNameRoute = WorkersRoutesRouteNameRouteImport.update({
  id: '/$routeName',
  path: '/$routeName',
  getParentRoute: () => WorkersRoutesRoute,
} as any)
const WorkersServicesIndexRoute = WorkersServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkersServicesRoute,
} as any)
const WorkersServicesServiceNameRoute =
  WorkersServicesServiceNameRouteImport.update({
    id: '/$serviceName',
    path: '/$serviceName',
    getParentRoute: () => WorkersServicesRoute,
  } as any)
const BuildsJobIdBuildsBuildIdRoute =
  BuildsJobIdBuildsBuildIdRouteImport.update({
    id: '/builds/$buildId',
    path: '/builds/$buildId',
    getParentRoute: () => BuildsJobIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/builds': typeof BuildsRouteWithChildren
  '/cache': typeof CacheRoute
  '/credentials': typeof CredentialsRoute
  '/login': typeof LoginRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/releases': typeof ReleasesRouteWithChildren
  '/secrets': typeof SecretsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/workers': typeof WorkersRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/artifacts/$componentId': typeof ArtifactsComponentIdRoute
  '/artifacts/settings': typeof ArtifactsSettingsRoute
  '/builds/$jobId': typeof BuildsJobIdRouteWithChildren
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
  '/projects/$projectName': typeof ProjectsProjectNameRouteWithChildren
  '/releases/$releaseName': typeof ReleasesReleaseNameRoute
  '/releases/artifacts': typeof ReleasesArtifactsRoute
  '/releases/calendar': typeof ReleasesCalendarRoute
  '/secrets/$secretId': typeof SecretsSecretIdRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/workers/builds': typeof WorkersBuildsRouteWithChildren
  '/workers/deployments': typeof WorkersDeploymentsRouteWithChildren
  '/workers/overview': typeof WorkersOverviewRoute
  '/workers/persistentvolumeclaims': typeof WorkersPersistentvolumeclaimsRouteWithChildren
  '/workers/pods': typeof WorkersPodsRouteWithChildren
  '/workers/projects': typeof WorkersProjectsRouteWithChildren
  '/workers/routes': typeof WorkersRoutesRouteWithChildren
  '/workers/services': typeof WorkersServicesRouteWithChildren
  '/artifacts/': typeof ArtifactsIndexRoute
  '/builds/': typeof BuildsIndexRoute
  '/releases/': typeof ReleasesIndexRoute
  '/secrets/': typeof SecretsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/session/$': typeof ApiSessionSplatRoute
  '/projects/$projectName/branches': typeof ProjectsProjectNameBranchesRoute
  '/projects/$projectName/tags': typeof ProjectsProjectNameTagsRoute
  '/workers/builds/$buildName': typeof WorkersBuildsBuildNameRoute
  '/workers/deployments/$deploymentName': typeof WorkersDeploymentsDeploymentNameRoute
  '/workers/persistentvolumeclaims/$claimName': typeof WorkersPersistentvolumeclaimsClaimNameRoute
  '/workers/pods/$podName': typeof WorkersPodsPodNameRoute
  '/workers/projects/$projectName': typeof WorkersProjectsProjectNameRoute
  '/workers/routes/$routeName': typeof WorkersRoutesRouteNameRoute
  '/workers/services/$serviceName': typeof WorkersServicesServiceNameRoute
  '/builds/$jobId/': typeof BuildsJobIdIndexRoute
  '/projects/$projectName/': typeof ProjectsProjectNameIndexRoute
  '/workers/builds/': typeof WorkersBuildsIndexRoute
  '/workers/deployments/': typeof WorkersDeploymentsIndexRoute
  '/workers/persistentvolumeclaims/': typeof WorkersPersistentvolumeclaimsIndexRoute
  '/workers/pods/': typeof WorkersPodsIndexRoute
  '/workers/projects/': typeof WorkersProjectsIndexRoute
  '/workers/routes/': typeof WorkersRoutesIndexRoute
  '/workers/services/': typeof WorkersServicesIndexRoute
  '/builds/$jobId/builds/$buildId': typeof BuildsJobIdBuildsBuildIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cache': typeof CacheRoute
  '/credentials': typeof CredentialsRoute
  '/login': typeof LoginRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/workers': typeof WorkersRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/artifacts/$componentId': typeof ArtifactsComponentIdRoute
  '/artifacts/settings': typeof ArtifactsSettingsRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
  '/releases/$releaseName': typeof ReleasesReleaseNameRoute
  '/releases/artifacts': typeof ReleasesArtifactsRoute
  '/releases/calendar': typeof ReleasesCalendarRoute
  '/secrets/$secretId': typeof SecretsSecretIdRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/workers/overview': typeof WorkersOverviewRoute
  '/artifacts': typeof ArtifactsIndexRoute
  '/builds': typeof BuildsIndexRoute
  '/releases': typeof ReleasesIndexRoute
  '/secrets': typeof SecretsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/session/$': typeof ApiSessionSplatRoute
  '/projects/$projectName/branches': typeof ProjectsProjectNameBranchesRoute
  '/projects/$projectName/tags': typeof ProjectsProjectNameTagsRoute
  '/workers/builds/$buildName': typeof WorkersBuildsBuildNameRoute
  '/workers/deployments/$deploymentName': typeof WorkersDeploymentsDeploymentNameRoute
  '/workers/persistentvolumeclaims/$claimName': typeof WorkersPersistentvolumeclaimsClaimNameRoute
  '/workers/pods/$podName': typeof WorkersPodsPodNameRoute
  '/workers/projects/$projectName': typeof WorkersProjectsProjectNameRoute
  '/workers/routes/$routeName': typeof WorkersRoutesRouteNameRoute
  '/workers/services/$serviceName': typeof WorkersServicesServiceNameRoute
  '/builds/$jobId': typeof BuildsJobIdIndexRoute
  '/projects/$projectName': typeof ProjectsProjectNameIndexRoute
  '/workers/builds': typeof WorkersBuildsIndexRoute
  '/workers/deployments': typeof WorkersDeploymentsIndexRoute
  '/workers/persistentvolumeclaims': typeof WorkersPersistentvolumeclaimsIndexRoute
  '/workers/pods': typeof WorkersPodsIndexRoute
  '/workers/projects': typeof WorkersProjectsIndexRoute
  '/workers/routes': typeof WorkersRoutesIndexRoute
  '/workers/services': typeof WorkersServicesIndexRoute
  '/builds/$jobId/builds/$buildId': typeof BuildsJobIdBuildsBuildIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/builds': typeof BuildsRouteWithChildren
  '/cache': typeof CacheRoute
  '/credentials': typeof CredentialsRoute
  '/login': typeof LoginRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/releases': typeof ReleasesRouteWithChildren
  '/secrets': typeof SecretsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/workers': typeof WorkersRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/artifacts/$componentId': typeof ArtifactsComponentIdRoute
  '/artifacts/settings': typeof ArtifactsSettingsRoute
  '/builds/$jobId': typeof BuildsJobIdRouteWithChildren
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
  '/projects/$projectName': typeof ProjectsProjectNameRouteWithChildren
  '/releases/$releaseName': typeof ReleasesReleaseNameRoute
  '/releases/artifacts': typeof ReleasesArtifactsRoute
  '/releases/calendar': typeof ReleasesCalendarRoute
  '/secrets/$secretId': typeof SecretsSecretIdRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/workers/builds': typeof WorkersBuildsRouteWithChildren
  '/workers/deployments': typeof WorkersDeploymentsRouteWithChildren
  '/workers/overview': typeof WorkersOverviewRoute
  '/workers/persistentvolumeclaims': typeof WorkersPersistentvolumeclaimsRouteWithChildren
  '/workers/pods': typeof WorkersPodsRouteWithChildren
  '/workers/projects': typeof WorkersProjectsRouteWithChildren
  '/workers/routes': typeof WorkersRoutesRouteWithChildren
  '/workers/services': typeof WorkersServicesRouteWithChildren
  '/artifacts/': typeof ArtifactsIndexRoute
  '/builds/': typeof BuildsIndexRoute
  '/releases/': typeof ReleasesIndexRoute
  '/secrets/': typeof SecretsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/session/$': typeof ApiSessionSplatRoute
  '/projects/$projectName/branches': typeof ProjectsProjectNameBranchesRoute
  '/projects/$projectName/tags': typeof ProjectsProjectNameTagsRoute
  '/workers/builds/$buildName': typeof WorkersBuildsBuildNameRoute
  '/workers/deployments/$deploymentName': typeof WorkersDeploymentsDeploymentNameRoute
  '/workers/persistentvolumeclaims/$claimName': typeof WorkersPersistentvolumeclaimsClaimNameRoute
  '/workers/pods/$podName': typeof WorkersPodsPodNameRoute
  '/workers/projects/$projectName': typeof WorkersProjectsProjectNameRoute
  '/workers/routes/$routeName': typeof WorkersRoutesRouteNameRoute
  '/workers/services/$serviceName': typeof WorkersServicesServiceNameRoute
  '/builds/$jobId/': typeof BuildsJobIdIndexRoute
  '/projects/$projectName/': typeof ProjectsProjectNameIndexRoute
  '/workers/builds/': typeof WorkersBuildsIndexRoute
  '/workers/deployments/': typeof WorkersDeploymentsIndexRoute
  '/workers/persistentvolumeclaims/': typeof WorkersPersistentvolumeclaimsIndexRoute
  '/workers/pods/': typeof WorkersPodsIndexRoute
  '/workers/projects/': typeof WorkersProjectsIndexRoute
  '/workers/routes/': typeof WorkersRoutesIndexRoute
  '/workers/services/': typeof WorkersServicesIndexRoute
  '/builds/$jobId/builds/$buildId': typeof BuildsJobIdBuildsBuildIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/builds'
    | '/cache'
    | '/credentials'
    | '/login'
    | '/pipelines'
    | '/projects'
    | '/releases'
    | '/secrets'
    | '/settings'
    | '/workers'
    | '/api/health'
    | '/artifacts/$componentId'
    | '/artifacts/settings'
    | '/builds/$jobId'
    | '/invite/$invitationId'
    | '/pipelines/$pipelineId'
    | '/projects/$projectName'
    | '/releases/$releaseName'
    | '/releases/artifacts'
    | '/releases/calendar'
    | '/secrets/$secretId'
    | '/settings/organization'
    | '/workers/builds'
    | '/workers/deployments'
    | '/workers/overview'
    | '/workers/persistentvolumeclaims'
    | '/workers/pods'
    | '/workers/projects'
    | '/workers/routes'
    | '/workers/services'
    | '/artifacts/'
    | '/builds/'
    | '/releases/'
    | '/secrets/'
    | '/settings/'
    | '/api/session/$'
    | '/projects/$projectName/branches'
    | '/projects/$projectName/tags'
    | '/workers/builds/$buildName'
    | '/workers/deployments/$deploymentName'
    | '/workers/persistentvolumeclaims/$claimName'
    | '/workers/pods/$podName'
    | '/workers/projects/$projectName'
    | '/workers/routes/$routeName'
    | '/workers/services/$serviceName'
    | '/builds/$jobId/'
    | '/projects/$projectName/'
    | '/workers/builds/'
    | '/workers/deployments/'
    | '/workers/persistentvolumeclaims/'
    | '/workers/pods/'
    | '/workers/projects/'
    | '/workers/routes/'
    | '/workers/services/'
    | '/builds/$jobId/builds/$buildId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cache'
    | '/credentials'
    | '/login'
    | '/pipelines'
    | '/projects'
    | '/workers'
    | '/api/health'
    | '/artifacts/$componentId'
    | '/artifacts/settings'
    | '/invite/$invitationId'
    | '/pipelines/$pipelineId'
    | '/releases/$releaseName'
    | '/releases/artifacts'
    | '/releases/calendar'
    | '/secrets/$secretId'
    | '/settings/organization'
    | '/workers/overview'
    | '/artifacts'
    | '/builds'
    | '/releases'
    | '/secrets'
    | '/settings'
    | '/api/session/$'
    | '/projects/$projectName/branches'
    | '/projects/$projectName/tags'
    | '/workers/builds/$buildName'
    | '/workers/deployments/$deploymentName'
    | '/workers/persistentvolumeclaims/$claimName'
    | '/workers/pods/$podName'
    | '/workers/projects/$projectName'
    | '/workers/routes/$routeName'
    | '/workers/services/$serviceName'
    | '/builds/$jobId'
    | '/projects/$projectName'
    | '/workers/builds'
    | '/workers/deployments'
    | '/workers/persistentvolumeclaims'
    | '/workers/pods'
    | '/workers/projects'
    | '/workers/routes'
    | '/workers/services'
    | '/builds/$jobId/builds/$buildId'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/builds'
    | '/cache'
    | '/credentials'
    | '/login'
    | '/pipelines'
    | '/projects'
    | '/releases'
    | '/secrets'
    | '/settings'
    | '/workers'
    | '/api/health'
    | '/artifacts/$componentId'
    | '/artifacts/settings'
    | '/builds/$jobId'
    | '/invite/$invitationId'
    | '/pipelines/$pipelineId'
    | '/projects/$projectName'
    | '/releases/$releaseName'
    | '/releases/artifacts'
    | '/releases/calendar'
    | '/secrets/$secretId'
    | '/settings/organization'
    | '/workers/builds'
    | '/workers/deployments'
    | '/workers/overview'
    | '/workers/persistentvolumeclaims'
    | '/workers/pods'
    | '/workers/projects'
    | '/workers/routes'
    | '/workers/services'
    | '/artifacts/'
    | '/builds/'
    | '/releases/'
    | '/secrets/'
    | '/settings/'
    | '/api/session/$'
    | '/projects/$projectName/branches'
    | '/projects/$projectName/tags'
    | '/workers/builds/$buildName'
    | '/workers/deployments/$deploymentName'
    | '/workers/persistentvolumeclaims/$claimName'
    | '/workers/pods/$podName'
    | '/workers/projects/$projectName'
    | '/workers/routes/$routeName'
    | '/workers/services/$serviceName'
    | '/builds/$jobId/'
    | '/projects/$projectName/'
    | '/workers/builds/'
    | '/workers/deployments/'
    | '/workers/persistentvolumeclaims/'
    | '/workers/pods/'
    | '/workers/projects/'
    | '/workers/routes/'
    | '/workers/services/'
    | '/builds/$jobId/builds/$buildId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRouteWithChildren
  BuildsRoute: typeof BuildsRouteWithChildren
  CacheRoute: typeof CacheRoute
  CredentialsRoute: typeof CredentialsRoute
  LoginRoute: typeof LoginRoute
  PipelinesRoute: typeof PipelinesRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReleasesRoute: typeof ReleasesRouteWithChildren
  SecretsRoute: typeof SecretsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  WorkersRoute: typeof WorkersRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  ApiSessionSplatRoute: typeof ApiSessionSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds': {
      id: '/builds'
      path: '/builds'
      fullPath: '/builds'
      preLoaderRoute: typeof BuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache': {
      id: '/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof CacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/': {
      id: '/artifacts/'
      path: '/'
      fullPath: '/artifacts/'
      preLoaderRoute: typeof ArtifactsIndexRouteImport
      parentRoute: typeof ArtifactsRoute
    }
    '/artifacts/$componentId': {
      id: '/artifacts/$componentId'
      path: '/$componentId'
      fullPath: '/artifacts/$componentId'
      preLoaderRoute: typeof ArtifactsComponentIdRouteImport
      parentRoute: typeof ArtifactsRoute
    }
    '/artifacts/settings': {
      id: '/artifacts/settings'
      path: '/settings'
      fullPath: '/artifacts/settings'
      preLoaderRoute: typeof ArtifactsSettingsRouteImport
      parentRoute: typeof ArtifactsRoute
    }
    '/builds/': {
      id: '/builds/'
      path: '/'
      fullPath: '/builds/'
      preLoaderRoute: typeof BuildsIndexRouteImport
      parentRoute: typeof BuildsRoute
    }
    '/builds/$jobId': {
      id: '/builds/$jobId'
      path: '/$jobId'
      fullPath: '/builds/$jobId'
      preLoaderRoute: typeof BuildsJobIdRouteImport
      parentRoute: typeof BuildsRoute
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/$pipelineId': {
      id: '/pipelines/$pipelineId'
      path: '/$pipelineId'
      fullPath: '/pipelines/$pipelineId'
      preLoaderRoute: typeof PipelinesPipelineIdRouteImport
      parentRoute: typeof PipelinesRoute
    }
    '/projects/$projectName': {
      id: '/projects/$projectName'
      path: '/$projectName'
      fullPath: '/projects/$projectName'
      preLoaderRoute: typeof ProjectsProjectNameRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/releases/': {
      id: '/releases/'
      path: '/'
      fullPath: '/releases/'
      preLoaderRoute: typeof ReleasesIndexRouteImport
      parentRoute: typeof ReleasesRoute
    }
    '/releases/$releaseName': {
      id: '/releases/$releaseName'
      path: '/$releaseName'
      fullPath: '/releases/$releaseName'
      preLoaderRoute: typeof ReleasesReleaseNameRouteImport
      parentRoute: typeof ReleasesRoute
    }
    '/releases/artifacts': {
      id: '/releases/artifacts'
      path: '/artifacts'
      fullPath: '/releases/artifacts'
      preLoaderRoute: typeof ReleasesArtifactsRouteImport
      parentRoute: typeof ReleasesRoute
    }
    '/releases/calendar': {
      id: '/releases/calendar'
      path: '/calendar'
      fullPath: '/releases/calendar'
      preLoaderRoute: typeof ReleasesCalendarRouteImport
      parentRoute: typeof ReleasesRoute
    }
    '/secrets/': {
      id: '/secrets/'
      path: '/'
      fullPath: '/secrets/'
      preLoaderRoute: typeof SecretsIndexRouteImport
      parentRoute: typeof SecretsRoute
    }
    '/secrets/$secretId': {
      id: '/secrets/$secretId'
      path: '/$secretId'
      fullPath: '/secrets/$secretId'
      preLoaderRoute: typeof SecretsSecretIdRouteImport
      parentRoute: typeof SecretsRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/organization': {
      id: '/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof SettingsOrganizationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/workers/builds': {
      id: '/workers/builds'
      path: '/builds'
      fullPath: '/workers/builds'
      preLoaderRoute: typeof WorkersBuildsRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/workers/deployments': {
      id: '/workers/deployments'
      path: '/deployments'
      fullPath: '/workers/deployments'
      preLoaderRoute: typeof WorkersDeploymentsRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/workers/overview': {
      id: '/workers/overview'
      path: '/overview'
      fullPath: '/workers/overview'
      preLoaderRoute: typeof WorkersOverviewRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/workers/persistentvolumeclaims': {
      id: '/workers/persistentvolumeclaims'
      path: '/persistentvolumeclaims'
      fullPath: '/workers/persistentvolumeclaims'
      preLoaderRoute: typeof WorkersPersistentvolumeclaimsRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/workers/pods': {
      id: '/workers/pods'
      path: '/pods'
      fullPath: '/workers/pods'
      preLoaderRoute: typeof WorkersPodsRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/workers/projects': {
      id: '/workers/projects'
      path: '/projects'
      fullPath: '/workers/projects'
      preLoaderRoute: typeof WorkersProjectsRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/workers/routes': {
      id: '/workers/routes'
      path: '/routes'
      fullPath: '/workers/routes'
      preLoaderRoute: typeof WorkersRoutesRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/workers/services': {
      id: '/workers/services'
      path: '/services'
      fullPath: '/workers/services'
      preLoaderRoute: typeof WorkersServicesRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/api/session/$': {
      id: '/api/session/$'
      path: '/api/session/$'
      fullPath: '/api/session/$'
      preLoaderRoute: typeof ApiSessionSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/$jobId/': {
      id: '/builds/$jobId/'
      path: '/'
      fullPath: '/builds/$jobId/'
      preLoaderRoute: typeof BuildsJobIdIndexRouteImport
      parentRoute: typeof BuildsJobIdRoute
    }
    '/projects/$projectName/': {
      id: '/projects/$projectName/'
      path: '/'
      fullPath: '/projects/$projectName/'
      preLoaderRoute: typeof ProjectsProjectNameIndexRouteImport
      parentRoute: typeof ProjectsProjectNameRoute
    }
    '/projects/$projectName/branches': {
      id: '/projects/$projectName/branches'
      path: '/branches'
      fullPath: '/projects/$projectName/branches'
      preLoaderRoute: typeof ProjectsProjectNameBranchesRouteImport
      parentRoute: typeof ProjectsProjectNameRoute
    }
    '/projects/$projectName/tags': {
      id: '/projects/$projectName/tags'
      path: '/tags'
      fullPath: '/projects/$projectName/tags'
      preLoaderRoute: typeof ProjectsProjectNameTagsRouteImport
      parentRoute: typeof ProjectsProjectNameRoute
    }
    '/workers/builds/': {
      id: '/workers/builds/'
      path: '/'
      fullPath: '/workers/builds/'
      preLoaderRoute: typeof WorkersBuildsIndexRouteImport
      parentRoute: typeof WorkersBuildsRoute
    }
    '/workers/builds/$buildName': {
      id: '/workers/builds/$buildName'
      path: '/$buildName'
      fullPath: '/workers/builds/$buildName'
      preLoaderRoute: typeof WorkersBuildsBuildNameRouteImport
      parentRoute: typeof WorkersBuildsRoute
    }
    '/workers/deployments/': {
      id: '/workers/deployments/'
      path: '/'
      fullPath: '/workers/deployments/'
      preLoaderRoute: typeof WorkersDeploymentsIndexRouteImport
      parentRoute: typeof WorkersDeploymentsRoute
    }
    '/workers/deployments/$deploymentName': {
      id: '/workers/deployments/$deploymentName'
      path: '/$deploymentName'
      fullPath: '/workers/deployments/$deploymentName'
      preLoaderRoute: typeof WorkersDeploymentsDeploymentNameRouteImport
      parentRoute: typeof WorkersDeploymentsRoute
    }
    '/workers/persistentvolumeclaims/': {
      id: '/workers/persistentvolumeclaims/'
      path: '/'
      fullPath: '/workers/persistentvolumeclaims/'
      preLoaderRoute: typeof WorkersPersistentvolumeclaimsIndexRouteImport
      parentRoute: typeof WorkersPersistentvolumeclaimsRoute
    }
    '/workers/persistentvolumeclaims/$claimName': {
      id: '/workers/persistentvolumeclaims/$claimName'
      path: '/$claimName'
      fullPath: '/workers/persistentvolumeclaims/$claimName'
      preLoaderRoute: typeof WorkersPersistentvolumeclaimsClaimNameRouteImport
      parentRoute: typeof WorkersPersistentvolumeclaimsRoute
    }
    '/workers/pods/': {
      id: '/workers/pods/'
      path: '/'
      fullPath: '/workers/pods/'
      preLoaderRoute: typeof WorkersPodsIndexRouteImport
      parentRoute: typeof WorkersPodsRoute
    }
    '/workers/pods/$podName': {
      id: '/workers/pods/$podName'
      path: '/$podName'
      fullPath: '/workers/pods/$podName'
      preLoaderRoute: typeof WorkersPodsPodNameRouteImport
      parentRoute: typeof WorkersPodsRoute
    }
    '/workers/projects/': {
      id: '/workers/projects/'
      path: '/'
      fullPath: '/workers/projects/'
      preLoaderRoute: typeof WorkersProjectsIndexRouteImport
      parentRoute: typeof WorkersProjectsRoute
    }
    '/workers/projects/$projectName': {
      id: '/workers/projects/$projectName'
      path: '/$projectName'
      fullPath: '/workers/projects/$projectName'
      preLoaderRoute: typeof WorkersProjectsProjectNameRouteImport
      parentRoute: typeof WorkersProjectsRoute
    }
    '/workers/routes/': {
      id: '/workers/routes/'
      path: '/'
      fullPath: '/workers/routes/'
      preLoaderRoute: typeof WorkersRoutesIndexRouteImport
      parentRoute: typeof WorkersRoutesRoute
    }
    '/workers/routes/$routeName': {
      id: '/workers/routes/$routeName'
      path: '/$routeName'
      fullPath: '/workers/routes/$routeName'
      preLoaderRoute: typeof WorkersRoutesRouteNameRouteImport
      parentRoute: typeof WorkersRoutesRoute
    }
    '/workers/services/': {
      id: '/workers/services/'
      path: '/'
      fullPath: '/workers/services/'
      preLoaderRoute: typeof WorkersServicesIndexRouteImport
      parentRoute: typeof WorkersServicesRoute
    }
    '/workers/services/$serviceName': {
      id: '/workers/services/$serviceName'
      path: '/$serviceName'
      fullPath: '/workers/services/$serviceName'
      preLoaderRoute: typeof WorkersServicesServiceNameRouteImport
      parentRoute: typeof WorkersServicesRoute
    }
    '/builds/$jobId/builds/$buildId': {
      id: '/builds/$jobId/builds/$buildId'
      path: '/builds/$buildId'
      fullPath: '/builds/$jobId/builds/$buildId'
      preLoaderRoute: typeof BuildsJobIdBuildsBuildIdRouteImport
      parentRoute: typeof BuildsJobIdRoute
    }
  }
}

interface ArtifactsRouteChildren {
  ArtifactsComponentIdRoute: typeof ArtifactsComponentIdRoute
  ArtifactsSettingsRoute: typeof ArtifactsSettingsRoute
  ArtifactsIndexRoute: typeof ArtifactsIndexRoute
}

const ArtifactsRouteChildren: ArtifactsRouteChildren = {
  ArtifactsComponentIdRoute: ArtifactsComponentIdRoute,
  ArtifactsSettingsRoute: ArtifactsSettingsRoute,
  ArtifactsIndexRoute: ArtifactsIndexRoute,
}

const ArtifactsRouteWithChildren = ArtifactsRoute._addFileChildren(
  ArtifactsRouteChildren,
)

interface BuildsJobIdRouteChildren {
  BuildsJobIdIndexRoute: typeof BuildsJobIdIndexRoute
  BuildsJobIdBuildsBuildIdRoute: typeof BuildsJobIdBuildsBuildIdRoute
}

const BuildsJobIdRouteChildren: BuildsJobIdRouteChildren = {
  BuildsJobIdIndexRoute: BuildsJobIdIndexRoute,
  BuildsJobIdBuildsBuildIdRoute: BuildsJobIdBuildsBuildIdRoute,
}

const BuildsJobIdRouteWithChildren = BuildsJobIdRoute._addFileChildren(
  BuildsJobIdRouteChildren,
)

interface BuildsRouteChildren {
  BuildsJobIdRoute: typeof BuildsJobIdRouteWithChildren
  BuildsIndexRoute: typeof BuildsIndexRoute
}

const BuildsRouteChildren: BuildsRouteChildren = {
  BuildsJobIdRoute: BuildsJobIdRouteWithChildren,
  BuildsIndexRoute: BuildsIndexRoute,
}

const BuildsRouteWithChildren =
  BuildsRoute._addFileChildren(BuildsRouteChildren)

interface PipelinesRouteChildren {
  PipelinesPipelineIdRoute: typeof PipelinesPipelineIdRoute
}

const PipelinesRouteChildren: PipelinesRouteChildren = {
  PipelinesPipelineIdRoute: PipelinesPipelineIdRoute,
}

const PipelinesRouteWithChildren = PipelinesRoute._addFileChildren(
  PipelinesRouteChildren,
)

interface ProjectsProjectNameRouteChildren {
  ProjectsProjectNameBranchesRoute: typeof ProjectsProjectNameBranchesRoute
  ProjectsProjectNameTagsRoute: typeof ProjectsProjectNameTagsRoute
  ProjectsProjectNameIndexRoute: typeof ProjectsProjectNameIndexRoute
}

const ProjectsProjectNameRouteChildren: ProjectsProjectNameRouteChildren = {
  ProjectsProjectNameBranchesRoute: ProjectsProjectNameBranchesRoute,
  ProjectsProjectNameTagsRoute: ProjectsProjectNameTagsRoute,
  ProjectsProjectNameIndexRoute: ProjectsProjectNameIndexRoute,
}

const ProjectsProjectNameRouteWithChildren =
  ProjectsProjectNameRoute._addFileChildren(ProjectsProjectNameRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectNameRoute: typeof ProjectsProjectNameRouteWithChildren
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectNameRoute: ProjectsProjectNameRouteWithChildren,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ReleasesRouteChildren {
  ReleasesReleaseNameRoute: typeof ReleasesReleaseNameRoute
  ReleasesArtifactsRoute: typeof ReleasesArtifactsRoute
  ReleasesCalendarRoute: typeof ReleasesCalendarRoute
  ReleasesIndexRoute: typeof ReleasesIndexRoute
}

const ReleasesRouteChildren: ReleasesRouteChildren = {
  ReleasesReleaseNameRoute: ReleasesReleaseNameRoute,
  ReleasesArtifactsRoute: ReleasesArtifactsRoute,
  ReleasesCalendarRoute: ReleasesCalendarRoute,
  ReleasesIndexRoute: ReleasesIndexRoute,
}

const ReleasesRouteWithChildren = ReleasesRoute._addFileChildren(
  ReleasesRouteChildren,
)

interface SecretsRouteChildren {
  SecretsSecretIdRoute: typeof SecretsSecretIdRoute
  SecretsIndexRoute: typeof SecretsIndexRoute
}

const SecretsRouteChildren: SecretsRouteChildren = {
  SecretsSecretIdRoute: SecretsSecretIdRoute,
  SecretsIndexRoute: SecretsIndexRoute,
}

const SecretsRouteWithChildren =
  SecretsRoute._addFileChildren(SecretsRouteChildren)

interface SettingsRouteChildren {
  SettingsOrganizationRoute: typeof SettingsOrganizationRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsOrganizationRoute: SettingsOrganizationRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface WorkersBuildsRouteChildren {
  WorkersBuildsBuildNameRoute: typeof WorkersBuildsBuildNameRoute
  WorkersBuildsIndexRoute: typeof WorkersBuildsIndexRoute
}

const WorkersBuildsRouteChildren: WorkersBuildsRouteChildren = {
  WorkersBuildsBuildNameRoute: WorkersBuildsBuildNameRoute,
  WorkersBuildsIndexRoute: WorkersBuildsIndexRoute,
}

const WorkersBuildsRouteWithChildren = WorkersBuildsRoute._addFileChildren(
  WorkersBuildsRouteChildren,
)

interface WorkersDeploymentsRouteChildren {
  WorkersDeploymentsDeploymentNameRoute: typeof WorkersDeploymentsDeploymentNameRoute
  WorkersDeploymentsIndexRoute: typeof WorkersDeploymentsIndexRoute
}

const WorkersDeploymentsRouteChildren: WorkersDeploymentsRouteChildren = {
  WorkersDeploymentsDeploymentNameRoute: WorkersDeploymentsDeploymentNameRoute,
  WorkersDeploymentsIndexRoute: WorkersDeploymentsIndexRoute,
}

const WorkersDeploymentsRouteWithChildren =
  WorkersDeploymentsRoute._addFileChildren(WorkersDeploymentsRouteChildren)

interface WorkersPersistentvolumeclaimsRouteChildren {
  WorkersPersistentvolumeclaimsClaimNameRoute: typeof WorkersPersistentvolumeclaimsClaimNameRoute
  WorkersPersistentvolumeclaimsIndexRoute: typeof WorkersPersistentvolumeclaimsIndexRoute
}

const WorkersPersistentvolumeclaimsRouteChildren: WorkersPersistentvolumeclaimsRouteChildren =
  {
    WorkersPersistentvolumeclaimsClaimNameRoute:
      WorkersPersistentvolumeclaimsClaimNameRoute,
    WorkersPersistentvolumeclaimsIndexRoute:
      WorkersPersistentvolumeclaimsIndexRoute,
  }

const WorkersPersistentvolumeclaimsRouteWithChildren =
  WorkersPersistentvolumeclaimsRoute._addFileChildren(
    WorkersPersistentvolumeclaimsRouteChildren,
  )

interface WorkersPodsRouteChildren {
  WorkersPodsPodNameRoute: typeof WorkersPodsPodNameRoute
  WorkersPodsIndexRoute: typeof WorkersPodsIndexRoute
}

const WorkersPodsRouteChildren: WorkersPodsRouteChildren = {
  WorkersPodsPodNameRoute: WorkersPodsPodNameRoute,
  WorkersPodsIndexRoute: WorkersPodsIndexRoute,
}

const WorkersPodsRouteWithChildren = WorkersPodsRoute._addFileChildren(
  WorkersPodsRouteChildren,
)

interface WorkersProjectsRouteChildren {
  WorkersProjectsProjectNameRoute: typeof WorkersProjectsProjectNameRoute
  WorkersProjectsIndexRoute: typeof WorkersProjectsIndexRoute
}

const WorkersProjectsRouteChildren: WorkersProjectsRouteChildren = {
  WorkersProjectsProjectNameRoute: WorkersProjectsProjectNameRoute,
  WorkersProjectsIndexRoute: WorkersProjectsIndexRoute,
}

const WorkersProjectsRouteWithChildren = WorkersProjectsRoute._addFileChildren(
  WorkersProjectsRouteChildren,
)

interface WorkersRoutesRouteChildren {
  WorkersRoutesRouteNameRoute: typeof WorkersRoutesRouteNameRoute
  WorkersRoutesIndexRoute: typeof WorkersRoutesIndexRoute
}

const WorkersRoutesRouteChildren: WorkersRoutesRouteChildren = {
  WorkersRoutesRouteNameRoute: WorkersRoutesRouteNameRoute,
  WorkersRoutesIndexRoute: WorkersRoutesIndexRoute,
}

const WorkersRoutesRouteWithChildren = WorkersRoutesRoute._addFileChildren(
  WorkersRoutesRouteChildren,
)

interface WorkersServicesRouteChildren {
  WorkersServicesServiceNameRoute: typeof WorkersServicesServiceNameRoute
  WorkersServicesIndexRoute: typeof WorkersServicesIndexRoute
}

const WorkersServicesRouteChildren: WorkersServicesRouteChildren = {
  WorkersServicesServiceNameRoute: WorkersServicesServiceNameRoute,
  WorkersServicesIndexRoute: WorkersServicesIndexRoute,
}

const WorkersServicesRouteWithChildren = WorkersServicesRoute._addFileChildren(
  WorkersServicesRouteChildren,
)

interface WorkersRouteChildren {
  WorkersBuildsRoute: typeof WorkersBuildsRouteWithChildren
  WorkersDeploymentsRoute: typeof WorkersDeploymentsRouteWithChildren
  WorkersOverviewRoute: typeof WorkersOverviewRoute
  WorkersPersistentvolumeclaimsRoute: typeof WorkersPersistentvolumeclaimsRouteWithChildren
  WorkersPodsRoute: typeof WorkersPodsRouteWithChildren
  WorkersProjectsRoute: typeof WorkersProjectsRouteWithChildren
  WorkersRoutesRoute: typeof WorkersRoutesRouteWithChildren
  WorkersServicesRoute: typeof WorkersServicesRouteWithChildren
}

const WorkersRouteChildren: WorkersRouteChildren = {
  WorkersBuildsRoute: WorkersBuildsRouteWithChildren,
  WorkersDeploymentsRoute: WorkersDeploymentsRouteWithChildren,
  WorkersOverviewRoute: WorkersOverviewRoute,
  WorkersPersistentvolumeclaimsRoute:
    WorkersPersistentvolumeclaimsRouteWithChildren,
  WorkersPodsRoute: WorkersPodsRouteWithChildren,
  WorkersProjectsRoute: WorkersProjectsRouteWithChildren,
  WorkersRoutesRoute: WorkersRoutesRouteWithChildren,
  WorkersServicesRoute: WorkersServicesRouteWithChildren,
}

const WorkersRouteWithChildren =
  WorkersRoute._addFileChildren(WorkersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRouteWithChildren,
  BuildsRoute: BuildsRouteWithChildren,
  CacheRoute: CacheRoute,
  CredentialsRoute: CredentialsRoute,
  LoginRoute: LoginRoute,
  PipelinesRoute: PipelinesRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReleasesRoute: ReleasesRouteWithChildren,
  SecretsRoute: SecretsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  WorkersRoute: WorkersRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  ApiSessionSplatRoute: ApiSessionSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
